### ISSUE TITLE
Flexpaper显示问题

### ISSUE THREAD

**Issue by VincentWY** [yoozi/swf-docs-generator#13]
你好，我在用pdf2swf转换文档时用了参数-s poly2bitmap，转换出的swf文件在flexpaper中显示错位，调整flexpaper的参数均无效。该如何解决？

**Comment by chekun** [comment]
-s poly2bitmap 会影响排版的，如非必要，不要加此参数即可。
这个乱了就是乱了在swf文件中，和flexpaper没有关系了。

**Comment by VincentWY** [comment]
我的pdf文档是从doc转过来的，图形文件很多，不加这个参数经常转换失败

---

吴勇TEL：15152220520
Email：iunknownyong@foxmail.com

------------------ 原始邮件 ------------------
发件人: "Che Kun"; 
发送时间: 2013年11月25日(星期一) 下午2:20
收件人: "yoozi/swf-docs-generator"; 
抄送: "Vincent"; 
主题: Re: [swf-docs-generator] Flexpaper显示问题 (#13)

-s poly2bitmap 会影响排版的，如非必要，不要加此参数即可。

**Comment by chekun** [comment]
嗯，那就只能乱排版的样子看了。
我之前的项目中，是先尝试不加该参数进行转换，如果报图形数量多65535的时候，进加上此参数再转一次。没办法，有时候就得有牺牲。
