### ISSUE TITLE
easy_install 时会报错。

### ISSUE THREAD

**Issue by chiangtor** [yoozi/swf-docs-generator#14]
[swf-docs-generator/install.md at master · yoozi/swf-docs-generator](https://github.com/yoozi/swf-docs-generator/blob/master/install.md)

其中的

``` bash
$easy_install  supervisor
```

install Python之前需要安装https的支持

``` bash
$yum install openssl-devel
```

然后再编译 Python

**Comment by chekun** [comment]
Thanks.
