### ISSUE TITLE
服务启动问题

### ISSUE THREAD

**Issue by ym1623** [yoozi/swf-docs-generator#16]
当我修改scripts/services下的database配置，，发现里面有一个参数是read_dafult_file，这个是必填的吗？我装的mysql里面的路径没有这个东西，怎么办?

[root@Aoc services]# find / -name my.cnf
/etc/my.cnf
/usr/local/src/lnmp1.1-full/mysql-5.5.37/packaging/rpm-uln/my.cnf
/usr/local/src/lnmp1.1-full/mysql-5.5.37/packaging/rpm-oel/my.cnf
/usr/local/src/lnmp1.1-full/mysql-5.5.37/mysql-test/suite/rpl/my.cnf
/usr/local/src/lnmp1.1-full/mysql-5.5.37/mysql-test/suite/federated/my.cnf
/usr/local/mysql/mysql-test/suite/rpl/my.cnf
/usr/local/mysql/mysql-test/suite/federated/my.cnf

后面运行supervisorctl reload依然服务未启动

**Comment by chekun** [comment]
有兴趣的话，建议你使用以下类库重写，这个方案仅仅是个prototype.
1. https://github.com/ryancole/topdf
2. https://github.com/chekun/pdf2swf-nodejs
3. https://github.com/chekun/httpsqs-nodejs

**Comment by chekun** [comment]
另外，mysql 不一定非要用supervisor管理启动的。

**Comment by ym1623** [comment]
现在这个错误我解决了，，遇到一个很古怪的问题，就是加了两行vi /data/www/scripts/pyConverter.py

# import uno 前 加上两行

# import sys

# sys.path.append('/opt/libreoffice3.6/program')

后面报错：
File "/home/wwwroot/v.dev/scripts/services/../pyConverter.py", line 15, in <module>
    import uno
  File "/opt/libreoffice4.3/program/uno.py", line 21, in <module>
    import pyuno
ImportError: dynamic module does not define init function (initpyuno)
^CTraceback (most recent call last):
  File "/home/wwwroot/v.dev/scripts/services/office2pdf.py", line 39, in <module>
    convert()
  File "/home/wwwroot/v.dev/scripts/services/office2pdf.py", line 36, in convert
    time.sleep(1)

**Comment by ym1623** [comment]
我用的libreoffice版本是4.3

**Comment by chekun** [comment]
应该是libreoffice没有装好，或者这个版本的uno代码有变化。
见我在2楼回复的，自己写一个吧，不是很复杂。

**Comment by ym1623** [comment]
我现在完全都是按照你所说的版本按照的，libreoffice版本3.6，但是在运行office2pdf.py的时候报错
[root@Aoc services]#   File "../pyConverter.py", line 17, in <module>
-bash: syntax error near unexpected token `newline'
[root@Aoc services]#     from com.sun.star.beans import PropertyValue
-bash: from: command not found

**Comment by ym1623** [comment]
写一个也不是很复杂，，我就是觉得奇怪，为什么按照文档环境一样，服务也都安装了没有问题了，但是在pyConverter.py中却报错，以下是pyConverter.py的部分代码，，希望能帮我找到错误原因，谢谢！

#

# PyODConverter (Python OpenDocument Converter) v1.2 - 2012-03-10

#

# This script converts a document from one office format to another by

# connecting to an OpenOffice.org instance via Python-UNO bridge.

#

# Copyright (C) 2008-2012 Mirko Nasato

# Licensed under the GNU LGPL v2.1 - http://www.gnu.org/licenses/lgpl-2.1.html

# \- or any later version.

#
DEFAULT_OPENOFFICE_PORT = 8100

import sys
sys.path.append('/opt/libreoffice3.6/program')
import uno
from os.path import abspath, isfile, splitext
from com.sun.star.beans import PropertyValue
from com.sun.star.task import ErrorCodeIOException
from com.sun.star.connection import NoConnectException

FAMILY_TEXT = "Text"
FAMILY_WEB = "Web"
FAMILY_SPREADSHEET = "Spreadsheet"
FAMILY_PRESENTATION = "Presentation"
FAMILY_DRAWING = "Drawing"

**Comment by bcho** [comment]
@ym1623 你的 python 脚本没有写好 shebang，建议执行 `python pyConverter.py` 而不是直接 `./pyConverter.py`

**Comment by ym1623** [comment]
[root@Aoc scripts]# python pyConverter.py 
Traceback (most recent call last):
  File "pyConverter.py", line 17, in <module>
    from com.sun.star.beans import PropertyValue
ImportError: No module named com.sun.star.beans

**Comment by chekun** [comment]
其实就没有安装好，所以才会这么多问题。 :smiley:
