### ISSUE TITLE
我用的是apache服务器，所有都安装正常但是，按完之后

### ISSUE THREAD

**Issue by tjaol** [yoozi/swf-docs-generator#17]
![wenku](https://cloud.githubusercontent.com/assets/4272274/6500983/64a8de16-c345-11e4-82c5-da4d47f853d4.jpg)

**Comment by tjaol** [comment]
已上传列表和服务状态都显示不出来

**Comment by chekun** [comment]
你的静态资源没有加载出来，css啥的。
确认这些资源的能否被正确访问到。

**Comment by tjaol** [comment]
Oh！多谢，应该就是权限问题
