### ISSUE TITLE
关于服务器端的脚本

### ISSUE THREAD

**Issue by xiaozi** [yoozi/swf-docs-generator#3]
python本身就有队列，为什么还要用第三方的，我看了下源码，中间貌似多了好几个过程，查看文件的状态是通过数据库来判断的，这个应该没涉及到查看队列元素吧。

我是用thrift来做php和python之间的通信，然后开了几个线程处理队列，分别在线程里面调用转换程序

我写了个脚本demo [http://type.so/python/python-queue-document-convert-service.html](http://type.so/python/python-queue-document-convert-service.html)

**Comment by chekun** [comment]
我来简单回答一下
1.使用httpsqs是因为需要一个轻型持久化的队列服务
2.result = sqs.gets('pdf2swf')即是获取出队列元素
3.数据库操作只是用来更新状态，并非查看状态
4.显然你的python水平比我高，我还要多向你学习，呵呵
Thanks
