### ISSUE TITLE
求详细一点的教程

### ISSUE THREAD

**Issue by Jackroyal** [yoozi/swf-docs-generator#4]
项目的博客地址http://blog.yoozi.cn/opensource/swf-docs-generator/，已经打不开了，最近一直在找相关的资料，虽然实现的思路差不多，但是一直都没有看到一个完整的解决方案，而且各个方案都小有不同，对于一个新手来说，搭建还是比较困难，希望能有一个详细的搭建过程，谢谢

**Comment by chekun** [comment]
谢谢反馈，近期我回提供一个部署文档。

**Comment by chekun** [comment]
@Jackroyal 已经更新部署文档，嘿嘿。
