### ISSUE TITLE
浏览swf文件会丢失最后一页

### ISSUE THREAD

**Issue by fuhao715** [yoozi/swf-docs-generator#7]
在浏览文件的时候发现，若swf文件只有一页则无法显示；若两页，只能显示第一页而第二页的内容丢失也不报错。把swf直接拖放到浏览器则显示正常。请教您是否出现此问题。

**Comment by chekun** [comment]
@fuhao715 试一下升级一下flexpaper的版本哈

**Comment by fuhao715** [comment]
@chekun 找到原因是本地flash player 版本太低导致的。谢谢！
