### ISSUE TITLE
启动soffice服务，启动进程、监听端口正常；pyodconverter连接不上端口

### ISSUE THREAD

**Issue by fuhao715** [yoozi/swf-docs-generator#8]
```
$ soffice "-accept=socket,port=2002;urp;"
```

命令启动office服务，进程正常、端口未监听到；
采用

```
$ soffice --headless --accept="socket,host=127.0.0.1,port=2002;urp;" --nofirststartwizard &  
```

命令启动office服务，进程正常、端口监听正常；
pyodconverter连接不上端口。

**Comment by chekun** [comment]
贴出错误吧

**Comment by fuhao715** [comment]
DocumentConverter.py:116: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  self.message = message
DocumentConverter.py:119: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  return self.message
ERROR! failed to connect to OpenOffice.org on port 2002

![a](https://f.cloud.github.com/assets/551637/1378709/5e5c67dc-3ad7-11e3-91a2-d8d06d83406c.jpg)

**Comment by chekun** [comment]
你在1楼打的命令上启动是在127.0.0.1上的，你截图上的却又在10.23.4.155上了

**Comment by fuhao715** [comment]
不好意思，造成误解。启动命令是在10.23.4.155机器上执行的，LibreOffice也是安装在此机器上，把相应host更改为10.23.4.155和127.0.0.1都是一样的failed to connect to OpenOffice.org on port 2002，把2002更改为其它端口也不行。应用也是部署在这台linux机器上，也不存在防火墙等安全策略的问题。望不吝赐教。

**Comment by chekun** [comment]
OK, 看起来是pyodconverter的问题，你可以到 https://github.com/mirkonasato/pyodconverter 他的项目下进行咨询。

**Comment by fuhao715** [comment]
找了另外一台虚机同样方式安装，却可用。原因还是在这台虚机上可能有什么冲突了。还是谢谢你！
