### ISSUE TITLE
转换服务update数据失败

### ISSUE THREAD

**Issue by VincentWY** [yoozi/swf-docs-generator#9]
数据库采用InnoDB引擎，在read_default_file参数无效时，数据不被更新，需增加commit

**Comment by chekun** [comment]
嗯，这个项目是个DEMO，是个例子哈，距离直接实际使用还是有距离的。

**Comment by VincentWY** [comment]
Thx for reply!
我们现在刚好在做这样一套方案，还望多多指教

------------------ 原始邮件 ------------------
发件人: "Che Kun";notifications@github.com;
发送时间: 2013年11月14日(星期四) 中午11:53
收件人: "yoozi/swf-docs-generator"swf-docs-generator@noreply.github.com; 
抄送: "Vincent"iunknownyong@foxmail.com; 
主题: Re: [swf-docs-generator] 转换服务update数据失败 (#9)

嗯，这个项目是个DEMO，是个例子哈，距离直接实际使用还是有距离的。

**Comment by chekun** [comment]
指教不敢当，欢迎交流。

**Comment by VincentWY** [comment]
您好，您那边有libreoffice3.6的源吗，我从源码编译各种不过。。。

------------------ 原始邮件 ------------------
发件人: "Che Kun";notifications@github.com;
发送时间: 2013年11月14日(星期四) 中午1:33
收件人: "yoozi/swf-docs-generator"swf-docs-generator@noreply.github.com; 
抄送: "Vincent"iunknownyong@foxmail.com; 
主题: Re: [swf-docs-generator] 转换服务update数据失败 (#9)

指教不敢当，欢迎交流。

**Comment by chekun** [comment]
可以直接使用rpm安装
